### ISSUE TITLE
Installing thru proxy

### ISSUE THREAD

**Issue by fublu** [Netflix/stethoscope#69] opened 2017-09-15 12:05 UTC
Hi again

I run into problems running the docker-compose up
My server is behind a proxy and I get this error

tgj@stethoscope-test-1:~/stethoscope$ docker-compose up
Building login
Step 1/11 : FROM python:2.7
 ---> 5ca9b5ba555d
Step 2/11 : RUN apt-get update   && apt-get install -y --no-install-recommends freetds-dev   && rm -rf /var/lib/apt/lists/*
 ---> Running in ff8311e724c4
Err http://security.debian.org jessie/updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Unable to connect to security.debian.org:http: [IP: 217.196.149.233 80]
Err http://deb.debian.org jessie InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://deb.debian.org jessie Release.gpg
  Unable to connect to deb.debian.org:http: [IP: 128.31.0.62 80]
Err http://deb.debian.org jessie-updates Release.gpg
  Unable to connect to deb.debian.org:http: [IP: 128.31.0.62 80]
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Unable to connect to security.debian.org:http: [IP: 217.196.149.233 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Unable to connect to deb.debian.org:http: [IP: 128.31.0.62 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Unable to connect to deb.debian.org:http: [IP: 128.31.0.62 80]

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package freetds-dev
ERROR: Service 'login' failed to build: The command '/bin/sh -c apt-get update   && apt-get install -y --no-install-recommends freetds-dev   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

I have setup proxy in Docker 

stethoscope-test-1:~/stethoscope$ systemctl show --property=Environment docker               
Environment=HTTP_PROXY=http://proxy-1.int.stofa.net:3128/ HTTPS_PROXY=http://proxy-1.int.stofa.net:3128/

I have also tried adding http_proxy to the docker-compose.base.yml like this

version: '2'
services:
  base:
    build: .
    environment:
     - http_proxy
     - https_proxy

Nothing seem to work for me.

**Comment by fublu** [comment] 2017-09-15 13:00
we have fixed this issue but has now run into a new problem

Obtaining file:///code
    Complete output from command python setup.py egg_info:
    Not found: [u'git+https://github.com/duosecurity/duo_client_python.git@1cc71f80927b02e75773094c9dd77af1fc8e4064.zip#egg=duo_client-3.0',
    Not found: u'git+https://github.com/wrapp/txwebretry.git@df5014019cf3a5d501bc755b9ce46509c1b31351#egg=txwebretry-0.1.1']
    zip_safe flag not set; analyzing archive contents...
    
    Installed /code/.eggs/pytest_runner-2.12.1-py2.7.egg
    Searching for setuptools-scm
    Reading https://pypi.python.org/simple/setuptools-scm/
    Downloading https://pypi.python.org/packages/f2/4d/f79818ef2f6c129e81cc2d7622fa195fa4511457f1fb8140129f568bcf7c/setuptools_scm-1.15.6-py2.7.egg#md5=7eaa86e817a5d3f68aa69d77b4430bf3
    Best match: setuptools-scm 1.15.6
    Processing setuptools_scm-1.15.6-py2.7.egg
    Moving setuptools_scm-1.15.6-py2.7.egg to /code/.eggs
    
    Installed /code/.eggs/setuptools_scm-1.15.6-py2.7.egg
    Searching for setuptools-git
    Reading https://pypi.python.org/simple/setuptools-git/
    Downloading https://pypi.python.org/packages/d9/c5/396c2c06cc89d4ce2d8ccf1d7e6cf31b33d4466a7c65a67a992adb3c6f29/setuptools-git-1.2.tar.gz#md5=40b2ef7687a384ea144503c2e5bc67e2
    Best match: setuptools-git 1.2
    Processing setuptools-git-1.2.tar.gz
    Writing /tmp/easy_install-ukz7lb/setuptools-git-1.2/setup.cfg
    Running setuptools-git-1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ukz7lb/setuptools-git-1.2/egg-dist-tmp-ufD379
    Moving setuptools_git-1.2-py2.7.egg to /code/.eggs
    
    Installed /code/.eggs/setuptools_git-1.2-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/code/setup.py", line 218, in <module>
        setuptools.setup(**setup_params)
      File "/usr/local/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 471, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/setuptools_scm/integration.py", line 22, in version_keyword
      File "build/bdist.linux-x86_64/egg/setuptools_scm/__init__.py", line 119, in get_version
      File "build/bdist.linux-x86_64/egg/setuptools_scm/__init__.py", line 97, in _do_parse
    LookupError: setuptools-scm was unable to detect version for '/code'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /code/
Makefile:26: recipe for target 'install-editable-package' failed
make: *** [install-editable-package] Error 1
ERROR: Service 'login' failed to build: The command '/bin/sh -c https_proxy=proxy-1.int.stofa.net:3128 make install-editable-package' returned a non-zero code: 2

**Comment by andrewmwhite** [comment] 2017-09-15 14:02
The second error looks like it was caused by a recent change -- try
checking out the prior commit (
https://github.com/Netflix/stethoscope/commit/fefc05920a3eb54c0da30fb1d9638f130e29a6d6)
instead.

I'm on vacation until early next week but should have some time then to fix
the issue.

**Comment by andrewmwhite** [comment] 2017-09-20 07:07
This should be fixed via #70. Feel free to re-open if you continue to have the same issue.

**Closed by andrewmwhite** 2017-09-20 07:07 UTC
